name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Cache mdbook
        id: cache-mdbook
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-mdbook

      - name: rust install
        if: steps.cache-mdbook.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install
        if: steps.cache-mdbook.outputs.cache-hit != 'true'
        run: |
          cargo install mdbook
          cargo install -f mdbook-variables
          cargo install mdbook-linkcheck
          # change rust folder permission avoiding Cache init fail. C.F. https://github.com/actions/cache/issues/133
          sudo chown -R $(whoami):$(id -ng) ~/.cargo/

      - name: build
        run: mdbook build

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_KEY }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: book/html # The folder the action should deploy.
